function IndU = KN_IndUtility(T_index,gamma,...
                              beta,...
                              MExp_mat,... 
                              P_mat,...
                              vip_route)
%% TODO: need to change the coefficient matrix into 3D matrix 
%% so that we have the matrix all routes in every decision when 
%% we don't actually ship since every route is possible
    IndU = zeros(size(MExp_mat, 1), size(MExp_mat, 2));
    T = size(MExp_mat, 1)/length(vip_route);
    for i=1:length(vip_route)
        IndU((i-1)*T+1:i*T, 1:vip_route(i)) = gamma(i) + P_mat((i-1)*T+1:i*T, 1:vip_route(i))*...
            beta(i, 1) + MExp_mat((i-1)*T+1:i*T, 1:vip_route(i)) * beta(i, 2);
    end
end

