function IndU = KN_IndUtility(T_index,... 
                              gamma,...
                              beta,...
                              ID_mat)
    
    IndU = gamma + sum(ID_mat(T_index, [4,6]).*beta, 2);
end

